# This is similar to prod but stripping the docker swarm specific
# code so we can debug prod env locally.

services:
  backend:
    image: 982383527471.dkr.ecr.ca-central-1.amazonaws.com/todos/backend-rails
    working_dir: /app
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todos_dev
      - RAILS_ENV=production
      - SECRET_KEY_BASE=VerySecret111
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge