services:
  backend:
    image: 982383527471.dkr.ecr.ca-central-1.amazonaws.com/todos/backend-rails
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    working_dir: /app
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todos_prod
      - RAILS_ENV=production
      - SECRET_KEY_BASE=VerySecret111
    networks:
      - todos_network
    depends_on:
      - db

  db:
    image: postgres:14
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager  # Keep DB on manager for data persistence
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todos_prod
    ports:
      - "5432:5432"
    networks:
      - todos_network

volumes:
  postgres_data:
    driver: local

networks:
  todos_network:
    driver: overlay
    attachable: true