default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

production:
  primary: &primary_prod
    <<: *default
  cache:
    <<: *primary_prod
    database: todos_prod_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_prod
    database: todos_prod_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_prod
    database: todos_prod_cable
    migrations_paths: db/cable_migrate